name: Deploy to ghcr

on:
  push:
    branches: ["test"]
  # workflow_dispatch:


permissions:
  contents: read
  packages: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx          
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build, tag, and push 
        uses: docker/build-push-action@v6
        env:
          REGISTRY: ghcr.io
          ORGANIZATION: onboarding-serivce
          REPOSITORY: be-onboarding
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          tags: | 
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}:latest




